openapi: 3.0.3

info:
  title: ${{ values.name }}
  description: ${{ values.description }}
  version: 1.0.0
servers:
  - url: "https://helloapi.example.com/v1"
    description: Production API endpoint for the Hello World API

components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string

paths:
  /hello/{name}:
    get:
      operationId: sayHello
      description: say hello
      parameters:
        - name: name
          in: path
          required: true
          description: name of the individual to say hello to
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"