services:

  postgres:
    image: postgres:16-alpine
    container_name: idp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command: start-dev --import-realm
    container_name: idp_sso
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
     - ./keycloak:/opt/keycloak/data/import

  openldap:
    image: osixia/openldap:1.5.0
    container_name: idp_ldap
    command: --copy-service
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "mycompany.local"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./openldap/init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif

volumes:
  ldap_data:
    name: idp_ldap_data
  ldap_config:
    name: idp_ldap_config
  postgres_data:
    name: idp_postgres_data

networks:
  default:
    name: idp-dev
    driver: bridge